installation:
  kubernetesProvider: "EKS"
  cni:
    type: Calico
    ipam:
      type: Calico
  calicoNetwork:
    bgp: Disabled
    ipPools:
    - cidr: ${pod_cidr}
      encapsulation: ${calico_encap}
